name: kakao_map_flutter
description: kakao map flutter plugin using webview_flutter
version: 0.0.5
homepage: https://github.com/note11g/Kakao-Map-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.1
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: